var child = [
  { 'dupe': false, 'type': 4, 'name': 'dataerasure', 'dir': 'c0', 'linked': 1, 'url': 'http://localhost:3000/dataerasure/', 'fetched': true, 'code': 500, 'len': 4016, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 0, 0 ], 'sig': 0x7bd8d114 },
  { 'dupe': false, 'type': 4, 'name': 'profile', 'dir': 'c1', 'linked': 1, 'url': 'http://localhost:3000/profile/', 'fetched': true, 'code': 500, 'len': 1325, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 0, 0 ], 'sig': 0x7bd8d114 },
  { 'dupe': false, 'type': 4, 'name': 'rest', 'dir': 'c2', 'linked': 1, 'url': 'http://localhost:3000/rest/', 'fetched': true, 'code': 500, 'len': 3944, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 10, 0, 0, 0, 0 ], 'sig': 0xd7415489 },
  { 'dupe': false, 'type': 8, 'name': '1', 'dir': 'c3', 'linked': 1, 'url': 'http://localhost:3000/1', 'fetched': true, 'code': 200, 'len': 1987, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 2, 0, 0 ], 'sig': 0xc7c57bce },
  { 'dupe': false, 'type': 8, 'name': 'main.js', 'dir': 'c4', 'linked': 2, 'url': 'http://localhost:3000/main.js', 'fetched': true, 'code': 200, 'len': 397636, 'decl_mime': 'application/javascript', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 1, 0, 0 ], 'sig': 0x7bd78051 },
  { 'dupe': false, 'type': 8, 'name': 'polyfills.js', 'dir': 'c5', 'linked': 2, 'url': 'http://localhost:3000/polyfills.js', 'fetched': true, 'code': 200, 'len': 54568, 'decl_mime': 'application/javascript', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 1, 1, 0 ], 'sig': 0xcf866eee },
  { 'dupe': false, 'type': 8, 'name': 'redirect', 'dir': 'c6', 'linked': 1, 'url': 'http://localhost:3000/redirect', 'fetched': true, 'code': 500, 'len': 4043, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 4, 0, 1, 2, 0 ], 'sig': 0x8c6d9cab },
  { 'dupe': false, 'type': 8, 'name': 'runtime.js', 'dir': 'c7', 'linked': 2, 'url': 'http://localhost:3000/runtime.js', 'fetched': true, 'code': 200, 'len': 3228, 'decl_mime': 'application/javascript', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 1, 0, 0 ], 'sig': 0x7bd78051 },
  { 'dupe': false, 'type': 8, 'name': 'styles.css', 'dir': 'c8', 'linked': 2, 'url': 'http://localhost:3000/styles.css', 'fetched': true, 'code': 200, 'len': 400000, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 1, 0, 0 ], 'sig': 0x7bd78051 },
  { 'dupe': false, 'type': 8, 'name': 'vendor.js', 'dir': 'c9', 'linked': 2, 'url': 'http://localhost:3000/vendor.js', 'fetched': true, 'code': 200, 'len': 400000, 'decl_mime': 'application/javascript', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 1, 0, 0 ], 'sig': 0x7bd78051 },
  { 'dupe': false, 'type': 16, 'name': 'assets', 'dir': 'c10', 'linked': 2, 'url': 'http://localhost:3000/assets', 'fetched': true, 'code': 200, 'len': 1987, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 1, 1, 4, 0, 0 ], 'sig': 0x630cb1ee },
  { 'dupe': false, 'type': 32, 'name': 'file-upload', 'dir': 'c11', 'linked': 1, 'url': 'http://localhost:3000/file-upload', 'fetched': true, 'code': 200, 'len': 1987, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff }
];
