var child = [
  { 'dupe': false, 'type': 4, 'name': 'dataerasure', 'dir': 'c0', 'linked': 1, 'url': 'https://juice-shop.herokuapp.com/dataerasure/', 'fetched': true, 'code': 500, 'len': 2940, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 1, 0, 0, 0 ], 'sig': 0xd0b3adc4 },
  { 'dupe': false, 'type': 4, 'name': 'profile', 'dir': 'c1', 'linked': 1, 'url': 'https://juice-shop.herokuapp.com/profile/', 'fetched': true, 'code': 500, 'len': 1229, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 1, 0, 0, 0 ], 'sig': 0xd0b3adc4 },
  { 'dupe': false, 'type': 4, 'name': 'rest', 'dir': 'c2', 'linked': 1, 'url': 'https://juice-shop.herokuapp.com/rest/', 'fetched': true, 'code': 500, 'len': 2866, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 12, 4, 0, 0, 0 ], 'sig': 0xe8d74dee },
  { 'dupe': false, 'type': 8, 'name': '1', 'dir': 'c3', 'linked': 1, 'url': 'https://juice-shop.herokuapp.com/1', 'fetched': true, 'code': 200, 'len': 1987, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 2, 0, 0, 0 ], 'sig': 0xd74163ae },
  { 'dupe': false, 'type': 8, 'name': 'main.js', 'dir': 'c4', 'linked': 2, 'url': 'https://juice-shop.herokuapp.com/main.js', 'fetched': true, 'code': 200, 'len': 398376, 'decl_mime': 'application/javascript', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x20fe8c94 },
  { 'dupe': false, 'type': 8, 'name': 'polyfills.js', 'dir': 'c5', 'linked': 2, 'url': 'https://juice-shop.herokuapp.com/polyfills.js', 'fetched': true, 'code': 200, 'len': 54374, 'decl_mime': 'application/javascript', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 1, 0 ], 'sig': 0x79d47764 },
  { 'dupe': false, 'type': 8, 'name': 'redirect', 'dir': 'c6', 'linked': 1, 'url': 'https://juice-shop.herokuapp.com/redirect', 'fetched': true, 'code': 500, 'len': 2965, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 4, 2, 0, 2, 0 ], 'sig': 0xd74b906e },
  { 'dupe': false, 'type': 8, 'name': 'runtime.js', 'dir': 'c7', 'linked': 2, 'url': 'https://juice-shop.herokuapp.com/runtime.js', 'fetched': true, 'code': 200, 'len': 3210, 'decl_mime': 'application/javascript', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x20fe8c94 },
  { 'dupe': false, 'type': 8, 'name': 'styles.css', 'dir': 'c8', 'linked': 2, 'url': 'https://juice-shop.herokuapp.com/styles.css', 'fetched': true, 'code': 200, 'len': 400000, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x20fe8c94 },
  { 'dupe': false, 'type': 8, 'name': 'vendor.js', 'dir': 'c9', 'linked': 2, 'url': 'https://juice-shop.herokuapp.com/vendor.js', 'fetched': true, 'code': 200, 'len': 400000, 'decl_mime': 'application/javascript', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x20fe8c94 },
  { 'dupe': false, 'type': 16, 'name': 'assets', 'dir': 'c10', 'linked': 2, 'url': 'https://juice-shop.herokuapp.com/assets', 'fetched': true, 'code': 200, 'len': 1987, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 1, 4, 0, 0, 0 ], 'sig': 0x3826bd2b },
  { 'dupe': false, 'type': 32, 'name': 'file-upload', 'dir': 'c11', 'linked': 1, 'url': 'https://juice-shop.herokuapp.com/file-upload', 'fetched': true, 'code': 200, 'len': 1987, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff }
];
